// pnpm qa:check — the "always assign a QA" gate.
//
// Runs in order:
//   1. pnpm type-check
//   2. pnpm test:run
//   3. pnpm build      (optional; skipped when APEX_QA_SKIP_BUILD=1 — useful
//                       for the post-commit hook which would otherwise add
//                       several seconds to every commit)
//
// On any failure, captures the failing step + a truncated tail of stderr
// and writes an auto-feedback record so the bug surfaces in the same
// feedback channel as runtime errors.
//
// Exit code: 0 on success, 1 on any failure. The post-commit hook uses
// this to decide whether to write a record, but never blocks the commit
// itself (per synth pitfall: a failing QA must not block work).
//
// Invocation:
//   pnpm qa:check                  # full QA
//   APEX_QA_SKIP_BUILD=1 pnpm qa:check   # tests + types only (fast path)

import { spawnSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createReport } from "../src/lib/feedback";

const REPO_ROOT_FOR_CLEANUP = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);

function autoCleanupStaleIssues(): void {
  // Fire-and-forget: invoke `pnpm feedback:cleanup` after a successful
  // qa run so any stale [auto-qa] / [auto-security] GitHub issues from
  // earlier intermediate-commit failures get auto-closed. Failures are
  // logged but never break the qa-check return code — the gate itself
  // already passed; cleanup is best-effort grooming.
  try {
    const r = spawnSync("pnpm", ["--silent", "feedback:cleanup", "--qa-only"], {
      cwd: REPO_ROOT_FOR_CLEANUP,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      env: process.env,
    });
    const out = `${r.stdout ?? ""}${r.stderr ?? ""}`.trim();
    // Only surface non-empty output that mentions an actual close —
    // suppress the "no stale issues" common case so qa-check stays quiet.
    if (out && !out.startsWith("No stale auto-")) {
      console.log("");
      console.log(out);
    }
  } catch {
    // ignore — cleanup is opportunistic
  }
}

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

type StepResult = {
  name: string;
  ok: boolean;
  durationMs: number;
  output: string;
  exitCode: number | null;
};

function runStep(name: string, cmd: string, args: string[]): StepResult {
  const start = Date.now();
  const r = spawnSync(cmd, args, {
    cwd: REPO_ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    env: process.env,
  });
  const ok = r.status === 0;
  const output = `${r.stdout ?? ""}\n${r.stderr ?? ""}`.trim();
  return {
    name,
    ok,
    durationMs: Date.now() - start,
    output,
    exitCode: r.status,
  };
}

// Scrub potential credential leaks from subprocess output before it
// lands in a feedback record. Uses the shared SECRET_PATTERNS module
// (src/lib/secret-patterns.ts) — adding a new credential shape there
// propagates here automatically.
//
// Security review MEDIUM-2: subprocesses inherit process.env and could
// print env values into stdout/stderr (now or in a future test). The
// feedback record body asserts "no prompt content" but said nothing
// about credentials. Belt-and-braces redaction before persisting.
import { redactSecrets } from "../src/lib/secret-patterns";

function truncateTail(text: string, maxChars = 2000): string {
  const redacted = redactSecrets(text);
  if (redacted.length <= maxChars) return redacted;
  return `… (truncated to last ${maxChars} chars)\n${redacted.slice(-maxChars)}`;
}

function emitFailureRecord(failed: StepResult): void {
  try {
    createReport({
      kind: "bug",
      title: `[auto-qa] ${failed.name} failed`,
      description: [
        `**Step:** \`${failed.name}\``,
        `**Exit code:** \`${failed.exitCode ?? "(none)"}\``,
        `**Duration:** ${failed.durationMs}ms`,
        ``,
        `**Tail of output:**`,
        ``,
        "```",
        truncateTail(failed.output),
        "```",
        ``,
        `_Auto-generated by \`pnpm qa:check\` (post-commit QA gate). No prompt content is included._`,
      ].join("\n"),
      channel: "cli",
      auto: true,
      sourceProject: "apex-engine",
      signature: `qa:${failed.name}:${failed.exitCode}`,
      context: {
        tags: {
          step: failed.name,
          exitCode: failed.exitCode ?? "null",
          durationMs: failed.durationMs,
        },
      },
    });
  } catch (err) {
    console.error(
      `[qa-check] failed to write feedback record: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
}

function main(): number {
  const skipBuild = process.env.APEX_QA_SKIP_BUILD === "1";
  const steps: StepResult[] = [];

  steps.push(runStep("type-check", "pnpm", ["type-check"]));
  if (steps[steps.length - 1].ok) {
    steps.push(runStep("test:run", "pnpm", ["test:run"]));
  }
  if (!skipBuild && steps.every((s) => s.ok)) {
    steps.push(runStep("build", "pnpm", ["build"]));
  }

  console.log("");
  console.log("QA summary");
  console.log("──────────");
  for (const s of steps) {
    const icon = s.ok ? "✓" : "✗";
    console.log(`${icon} ${s.name.padEnd(12)} ${s.durationMs}ms`);
  }
  if (skipBuild) console.log("  (build skipped via APEX_QA_SKIP_BUILD=1)");

  const failed = steps.find((s) => !s.ok);
  if (failed) {
    console.log("");
    console.log(`✗ ${failed.name} FAILED — writing auto-feedback record`);
    emitFailureRecord(failed);
    console.log("");
    console.log("Last 40 lines of failing step:");
    const tail = failed.output.split("\n").slice(-40).join("\n");
    console.log(tail);
    return 1;
  }

  console.log("");
  console.log("✓ all checks passed");
  // After a clean qa-check run, sweep any stale [auto-qa] issues that
  // are still open on GitHub from earlier intermediate-commit hook
  // emissions. Safe by construction: if qa-check passes NOW, anything
  // it would have emitted in the past is by definition fixed.
  autoCleanupStaleIssues();
  return 0;
}

process.exitCode = main();
